Update extract-vaultwarden-binary.yml
处理获取最新版本号时返回null问题

diff --git a/.github/workflows/extract-vaultwarden-binary.yml b/.github/workflows/extract-vaultwarden-binary.yml
--- a/.github/workflows/extract-vaultwarden-binary.yml
+++ b/.github/workflows/extract-vaultwarden-binary.yml
@@ -25,15 +25,7 @@ jobs:
       #     username: ${{ secrets.DOCKER_USERNAME }}
       #     password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 3: 获取最新版本号
-      - name: Get GitHub release version
-        id: get_version
-        run: |
-          LATEST_VERSION=$(curl -s https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest | jq -r .tag_name)
-          echo "Latest Vaultwarden release version: $LATEST_VERSION"
-          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
-
-      # Step 4: 获取当前版本号
+      # Step 3: 获取当前版本号
       - name: Check or create vaultwarden_version file with default
         id: read_version
         run: |
@@ -45,6 +37,27 @@ jobs:
           fi
           echo "Current vaultwarden version: $CURRENT_VERSION"
           echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+
+
+      # Step 4: 获取最新版本号
+      - name: Get GitHub release version
+        id: get_version
+        run: |
+          LATEST_VERSION="${{ env.CURRENT_VERSION }}"
+          API_URL="https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest"
+          
+          if response=$(curl -sSf --retry 3 --retry-delay 5 "$API_URL"); then
+            if LATEST_VERSION=$(jq -r '.tag_name // empty' <<< "$response"); then
+              echo "Success: $LATEST_VERSION"
+            else
+              echo "jq parsing failed"
+            fi
+          else
+            echo "curl failed with status $?"
+          fi
+            
+          echo "Latest Vaultwarden release version: $LATEST_VERSION"
+          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
 
       # Step 5: 比较版本号
       - name: Compare versions and decide whether to proceed
